spring.application.name=demo

spring.datasource.url=jdbc:postgresql://dpg-d7vd6e5ckfvc73eg2fs0-a.virginia-postgres.render.com:5432/busdb_n6zp
spring.datasource.username=busdb_n6zp_user
spring.datasource.password=e4pcaKWBmSQD1khBL1ZW3sxXq5gCdjyN

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}